<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_packageFrame</name>
   <tag></tag>
   <elementGuidId>ef2f376c-e7a5-4975-a280-ec61970ecb45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;packageFrame&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='packageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>14d3acf5-7ece-49dd-aa72-2e6787194228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>allclasses-frame.html</value>
      <webElementGuid>bcdde824-79e7-407d-842d-76fd77b6a833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>84897aef-8e5c-46ca-ac8d-1c09d1a7aa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All classes and interfaces (except non-static nested types)</value>
      <webElementGuid>284e4d8d-53cf-4e5d-b73c-c4b6e2ab2027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftBottom&quot;]/iframe[1]</value>
      <webElementGuid>6a0c1079-39a8-4b0c-be3b-d8f8de4b6877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='packageFrame']</value>
      <webElementGuid>816cbfe2-bd08-479f-86bf-b0b9c8394042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/iframe</value>
      <webElementGuid>3148cfe4-61d4-4a74-b16a-b9b3416eb8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'allclasses-frame.html' and @name = 'packageFrame' and @title = 'All classes and interfaces (except non-static nested types)']</value>
      <webElementGuid>054e7ee5-b7f3-4924-aae5-4d3902f296e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
